// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-solutions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/solutions.ts
var solutions = [
  {
    slug: "data-centre",
    title: "Data Centre Solutions",
    path: "/solutions/data-centre",
    summary: "Dedicated facilities housing IT infrastructure like servers, storage, and networking gear, providing centralized, secure, and reliable computing power.",
    capabilities: [
      "Software & Servers",
      "Storage & Backup",
      "Networking Infrastructure",
      "Environment Monitoring"
    ]
  },
  {
    slug: "information-security",
    title: "Information Security",
    path: "/solutions/information-security",
    summary: "Protecting information and systems from unauthorized access with a combination of technologies, processes, and administrative controls.",
    capabilities: [
      "Cloud Security",
      "Incident Response",
      "Vulnerability Management",
      "Cryptography"
    ]
  },
  {
    slug: "it-service-management",
    title: "IT Service Management",
    path: "/solutions/it-service-management",
    summary: "Designing, delivering, managing, and improving IT services to meet business goals while focusing on end-user experience.",
    capabilities: [
      "Asset Management",
      "Change Management",
      "Service Desk",
      "Problem Management"
    ]
  },
  {
    slug: "infrastructure",
    title: "Infrastructure Solutions",
    path: "/solutions/infrastructure",
    summary: "Combination of hardware, software, network and components that support business operations and serve as the foundation for IT services.",
    capabilities: [
      "Physical Hardware",
      "Software Applications",
      "Cloud Services",
      "Data Storage"
    ]
  }
];
var company = {
  name: "Teather Connect",
  tagline: "Innovative IT Solutions & Technology Services",
  description: "Teather Connect delivers comprehensive IT and communications solutions for enterprise businesses, designed to improve operational efficiency, foster innovation, and reduce costs.",
  values: [
    {
      title: "Collaboration",
      description: "We believe in the power of teamwork and open communication to drive success."
    },
    {
      title: "Agility",
      description: "We provide technologies that quickly adapt to modern changing trends."
    },
    {
      title: "Security & Privacy",
      description: "We are dedicated to maintaining confidentiality and safeguarding data."
    }
  ],
  pages: [
    { title: "Home", path: "/" },
    { title: "Solutions", path: "/solutions" },
    { title: "About", path: "/about" },
    { title: "Contact", path: "/contact" }
  ],
  contact: {
    enquiries: "Use the contact form on the /contact page to reach the team.",
    contactPage: "/contact"
  }
};

// src/lib/mcp/tools/list-solutions.ts
var list_solutions_default = defineTool({
  name: "list_solutions",
  title: "List solutions",
  description: "List all Teather Connect IT solution offerings with their slug, summary and page path.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: solutions.map((s) => `${s.title} (${s.slug}) \u2014 ${s.summary} [${s.path}]`).join("\n")
      }
    ],
    structuredContent: { solutions }
  })
});

// src/lib/mcp/tools/get-solution.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var get_solution_default = defineTool2({
  name: "get_solution",
  title: "Get solution details",
  description: "Get the full details (summary and capabilities) of one Teather Connect solution by its slug.",
  inputSchema: {
    slug: z.string().min(1).describe(
      "Solution slug: data-centre, information-security, it-service-management or infrastructure."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const solution = solutions.find((s) => s.slug === slug.trim().toLowerCase());
    if (!solution) {
      throw new ToolError(
        `Unknown solution "${slug}". Available slugs: ${solutions.map((s) => s.slug).join(", ")}.`
      );
    }
    return {
      content: [
        {
          type: "text",
          text: `${solution.title}
${solution.summary}

Capabilities:
${solution.capabilities.map((c) => `- ${c}`).join("\n")}

Page: ${solution.path}`
        }
      ],
      structuredContent: { solution }
    };
  }
});

// src/lib/mcp/tools/get-company-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_company_info_default = defineTool3({
  name: "get_company_info",
  title: "Get company info",
  description: "Get public company information about Teather Connect: description, values, site pages and how to get in touch.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `${company.name} \u2014 ${company.tagline}

${company.description}

Values:
${company.values.map((v) => `- ${v.title}: ${v.description}`).join("\n")}

Pages:
${company.pages.map((p) => `- ${p.title}: ${p.path}`).join("\n")}

Enquiries: ${company.contact.enquiries}`
      }
    ],
    structuredContent: { company }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "brand-mirror",
  title: "Brand Mirror",
  version: "0.1.0",
  instructions: "Public tools for the Teather Connect website. Use `list_solutions` to browse IT solution offerings, `get_solution` for details of one offering, and `get_company_info` for company background, values and contact routes.",
  tools: [list_solutions_default, get_solution_default, get_company_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
